#!/usr/bin/env ruby

require_relative "parabola"
require_relative "gen-parabola-cmdline"

options = GenParabolaCmdline.parse(ARGV)
parabola = Parabola.new(w: options.w, x: options.x, y: options.y)
dx = (options.e - options.b)/options.n  # Size of step.

(0..options.n).each do |step|
   x = options.b + step*dx
   printf("%11.4E %11.4E\n", x, parabola[x])
end

