#!/usr/bin/env ruby

require_relative "parabola"
require_relative "gendata-cmdline"

options = GenDataCmdLine.parse(ARGV)
parabola = Parabola.new(w: options.w, x: options.x, y: options.y)
if (options.n == 0)
   exit
end
dx = (options.e - options.b)/options.n
(0..options.n).each do |step|
   x = options.b + step*dx
   printf("%11.4E %11.4E\n", x, parabola[x])
end

